# Generated by Django 5.2.7 on 2025-10-02 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relay_message_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_emails', models.TextField(help_text='coma-separado')),
                ('status', models.CharField(default='created', max_length=64)),
                ('location', models.URLField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relay_delivery_id', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=64)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('ts', models.DateTimeField()),
                ('raw', models.JSONField(default=dict)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relay.emailmessage')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('ts', models.DateTimeField()),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('raw', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'ts'], name='relay_event_kind_c3ad7f_idx'), models.Index(fields=['email'], name='relay_event_email_8cf17e_idx')],
            },
        ),
    ]
