# Generated by Django 5.2.7 on 2025-10-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='html',
            field=models.TextField(blank=True, help_text='Cuerpo HTML del mensaje', null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='text',
            field=models.TextField(blank=True, help_text='Cuerpo texto plano del mensaje', null=True),
        ),
    ]
