# Generated by Django 5.2.7 on 2025-10-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0002_emailmessage_html_emailmessage_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template_id', models.CharField(max_length=128)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('recipients_file', models.FileField(upload_to='bulk_recipients/')),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('log', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
