# Generated by Django 5.1.1 on 2025-10-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0003_bulksend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bulksend',
            name='attachments',
        ),
        migrations.AddField(
            model_name='bulksend',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='relay.attachment'),
        ),
    ]
