# Generated by Django 5.1.1 on 2025-10-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0004_attachment_remove_bulksend_attachments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='from_email',
            field=models.EmailField(help_text='Correo del remitente', max_length=254, verbose_name='Remitente'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='html',
            field=models.TextField(blank=True, help_text='Contenido del correo en formato HTML', null=True, verbose_name='Contenido HTML'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='relay_message_id',
            field=models.CharField(blank=True, db_index=True, help_text='Se genera automáticamente al enviar el correo', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(help_text='Asunto del correo', max_length=255, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='text',
            field=models.TextField(blank=True, help_text='Versión en texto plano del correo', null=True, verbose_name='Contenido texto plano'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='to_emails',
            field=models.TextField(help_text='Lista de correos separados por coma', verbose_name='Destinatarios'),
        ),
    ]
