# Generated by Django 5.1.1 on 2025-10-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0005_alter_attachment_file_alter_emailmessage_from_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/%Y/%m/'),
        ),
    ]
