# Generated by Django 5.1.1 on 2025-10-07 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0006_alter_attachment_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(help_text='Email que se usará como remitente para los envíos', max_length=254, verbose_name='Email del remitente')),
                ('from_name', models.CharField(help_text='Nombre que aparecerá como remitente', max_length=255, verbose_name='Nombre del remitente')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si esta configuración está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de email de usuario',
                'verbose_name_plural': 'Configuraciones de email de usuarios',
            },
        ),
    ]
