# Generated by Django 5.1.1 on 2026-08-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '20260808120000_bulk_v2_real_send_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_type', models.CharField(choices=[('month', 'Month'), ('day', 'Day'), ('hour', 'Hour')], max_length=8)),
                ('window_start', models.DateTimeField()),
                ('limit_value', models.PositiveIntegerField()),
                ('consumed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ventana de cuota',
                'verbose_name_plural': 'Ventanas de cuota',
                'constraints': [models.UniqueConstraint(fields=('window_type', 'window_start'), name='uniq_quota_window'), models.CheckConstraint(condition=models.Q(('consumed__lte', models.F('limit_value'))), name='quota_window_consumed_lte_limit'), models.CheckConstraint(condition=models.Q(('window_type__in', ['month', 'day', 'hour'])), name='quota_window_valid_type')],
            },
        ),
    ]
