# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relay", "20251107120001_backgroundjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulksend",
            name="client_request_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
    ]
