# Generated by Django 5.2.14 on 2026-07-29 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '20260514150000_bulksend_client_request_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Adjunto', 'verbose_name_plural': 'Adjuntos'},
        ),
        migrations.AlterModelOptions(
            name='backgroundjob',
            options={'ordering': ('-created_at',), 'verbose_name': 'Trabajo en segundo plano', 'verbose_name_plural': 'Trabajos en segundo plano'},
        ),
        migrations.AlterModelOptions(
            name='bulksend',
            options={'verbose_name': 'Envio masivo', 'verbose_name_plural': 'Envios masivos'},
        ),
        migrations.AlterModelOptions(
            name='emailmessage',
            options={'verbose_name': 'Mensaje de correo', 'verbose_name_plural': 'Mensajes de correo'},
        ),
        migrations.AddField(
            model_name='bulksend',
            name='engine_version',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('v2', 'V2')], db_index=True, default='legacy', max_length=16),
        ),
        migrations.AddField(
            model_name='bulksend',
            name='import_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bulksend',
            name='import_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulksend',
            name='import_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulksend',
            name='import_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('importing', 'Importing'), ('ready', 'Ready'), ('ready_with_errors', 'Ready with errors'), ('error', 'Error')], db_index=True, default='not_started', max_length=24),
        ),
        migrations.AddField(
            model_name='bulksend',
            name='import_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulksend',
            name='imported_rows',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulksend',
            name='invalid_rows',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulksend',
            name='valid_rows',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BulkSendRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_version', models.PositiveIntegerField()),
                ('source_row_number', models.PositiveBigIntegerField()),
                ('recipient', models.TextField(blank=True, default='')),
                ('normalized_recipient', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(default=dict)),
                ('payload_hash', models.CharField(max_length=64)),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('invalid', 'Invalid')], default='pending', max_length=16)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_message', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bulk_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_occurrences', to='relay.bulksend')),
            ],
            options={
                'verbose_name': 'Ocurrencia de destinatario',
                'verbose_name_plural': 'Ocurrencias de destinatarios',
                'indexes': [models.Index(fields=['bulk_send', 'status'], name='bulk_recipient_status_idx'), models.Index(fields=['bulk_send', 'import_version', 'source_row_number'], name='bulk_recipient_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('bulk_send', 'import_version', 'source_row_number'), name='uniq_bulk_import_source_row'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'invalid'])), name='bulk_recipient_valid_status'), models.CheckConstraint(condition=models.Q(('import_version__gte', 1)), name='bulk_recipient_import_version_gte_1'), models.CheckConstraint(condition=models.Q(('source_row_number__gte', 1)), name='bulk_recipient_source_row_gte_1')],
            },
        ),
    ]
