# Generated by Django 5.2.7 on 2025-10-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relay', '0007_useremailconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSendUserConfigProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Bulk Send (por remitente)',
                'verbose_name_plural': 'Bulk Sends (por remitente)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('relay.bulksend',),
        ),
    ]
